[regression-tests] Fixed odd js script bug in 01-rpl-up-route.csc
Somehow expression 'packets = packets.substr() + "*"' results
in a simble 'object' instead of a 'string'.
This causes an error 'TypeError: Cannot find function substr in object
*'

Reproducible with Cooja script execution and Rhino 1.7 release 4.